# Generated by Django 5.0.3 on 2024-10-31 07:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='작업명')),
                ('description', models.TextField(verbose_name='작업 설명')),
                ('status', models.CharField(choices=[('TODO', '예정'), ('IN_PROGRESS', '진행중'), ('REVIEW', '검토중'), ('DONE', '완료'), ('HOLD', '보류')], default='TODO', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('URGENT', '긴급')], default='MEDIUM', max_length=20, verbose_name='우선순위')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('due_date', models.DateTimeField(verbose_name='마감일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('estimated_hours', models.FloatField(blank=True, null=True, verbose_name='예상 소요 시간')),
                ('actual_hours', models.FloatField(blank=True, null=True, verbose_name='실제 소요 시간')),
                ('difficulty', models.CharField(choices=[('EASY', '쉬움'), ('MEDIUM', '보통'), ('HARD', '어려움'), ('VERY_HARD', '매우 어려움')], default='MEDIUM', max_length=20, verbose_name='난이도')),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.department', verbose_name='담당 부서')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL, verbose_name='보고자')),
            ],
            options={
                'verbose_name': '작업',
                'verbose_name_plural': '작업들',
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_attachments/', verbose_name='첨부파일')),
                ('filename', models.CharField(max_length=255, verbose_name='파일명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task', verbose_name='작업')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='업로더')),
            ],
            options={
                'verbose_name': '작업 첨부파일',
                'verbose_name_plural': '작업 첨부파일들',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='작업')),
            ],
            options={
                'verbose_name': '작업 코멘트',
                'verbose_name_plural': '작업 코멘트들',
            },
        ),
        migrations.CreateModel(
            name='TaskEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('EASY', '쉬움'), ('MEDIUM', '보통'), ('HARD', '어려움'), ('VERY_HARD', '매우 어려움')], max_length=20, verbose_name='난이도')),
                ('performance_score', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='수행 점수')),
                ('feedback', models.TextField(verbose_name='피드백')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='평가자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='tasks.task', verbose_name='작업')),
            ],
            options={
                'verbose_name': '작업 평가',
                'verbose_name_plural': '작업 평가들',
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_status', models.CharField(choices=[('TODO', '예정'), ('IN_PROGRESS', '진행중'), ('REVIEW', '검토중'), ('DONE', '완료'), ('HOLD', '보류')], max_length=20, verbose_name='이전 상태')),
                ('new_status', models.CharField(choices=[('TODO', '예정'), ('IN_PROGRESS', '진행중'), ('REVIEW', '검토중'), ('DONE', '완료'), ('HOLD', '보류')], max_length=20, verbose_name='새로운 상태')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField(blank=True, verbose_name='변경 사유')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='변경자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task', verbose_name='작업')),
            ],
            options={
                'verbose_name': '작업 히스토리',
                'verbose_name_plural': '작업 히스토리들',
            },
        ),
        migrations.CreateModel(
            name='TaskTimeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(verbose_name='시작 시간')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('duration', models.DurationField(blank=True, null=True, verbose_name='소요 시간')),
                ('logged_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='기록자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_logs', to='tasks.task', verbose_name='작업')),
            ],
            options={
                'verbose_name': '작업 시간 로그',
                'verbose_name_plural': '작업 시간 로그들',
            },
        ),
    ]
