# Generated by Django 5.0.3 on 2024-10-28 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='작업명')),
                ('description', models.TextField(verbose_name='작업 설명')),
                ('status', models.CharField(choices=[('TODO', '예정'), ('IN_PROGRESS', '진행중'), ('REVIEW', '검토중'), ('DONE', '완료'), ('HOLD', '보류')], default='TODO', max_length=20, verbose_name='상태')),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('URGENT', '긴급')], default='MEDIUM', max_length=20, verbose_name='우선순위')),
                ('start_date', models.DateTimeField(verbose_name='시작일')),
                ('due_date', models.DateTimeField(verbose_name='마감일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to=settings.AUTH_USER_MODEL, verbose_name='담당자')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='organizations.department', verbose_name='담당 부서')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_tasks', to=settings.AUTH_USER_MODEL, verbose_name='보고자')),
            ],
            options={
                'verbose_name': '작업',
                'verbose_name_plural': '작업들',
            },
        ),
        migrations.CreateModel(
            name='TaskComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tasks.task', verbose_name='작업')),
            ],
            options={
                'verbose_name': '작업 코멘트',
                'verbose_name_plural': '작업 코멘트들',
            },
        ),
    ]
