# Generated by Django 5.0.3 on 2024-11-01 09:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_tasks', to='tasks.task', verbose_name='선행 작업'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_milestone',
            field=models.BooleanField(default=False, verbose_name='마일스톤 여부'),
        ),
        migrations.AddField(
            model_name='task',
            name='milestone_description',
            field=models.TextField(blank=True, null=True, verbose_name='마일스톤 설명'),
        ),
        migrations.AddField(
            model_name='task',
            name='working_hours',
            field=models.JSONField(default=dict, help_text='일별 작업 시간 기록', verbose_name='작업 시간'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['assignee', 'start_date', 'due_date'], name='tasks_task_assigne_b44075_idx'),
        ),
    ]
