# Generated by Django 5.0.3 on 2024-10-31 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('TASK_ASSIGNED', '작업 배정'), ('TASK_STATUS_CHANGED', '작업 상태 변경'), ('TASK_COMMENT', '작업 코멘트'), ('TASK_MENTION', '작업 멘션'), ('TASK_DUE_SOON', '작업 마감 임박'), ('TASK_OVERDUE', '작업 기한 초과')], max_length=30, verbose_name='알림 유형')),
                ('message', models.TextField(verbose_name='알림 내용')),
                ('is_read', models.BooleanField(default=False, verbose_name='읽음 여부')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='수신자')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task', verbose_name='관련 작업')),
            ],
            options={
                'verbose_name': '알림',
                'verbose_name_plural': '알림들',
            },
        ),
    ]
