# Generated by Django 5.0.3 on 2024-11-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='알림 만료 시간'),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('HIGH', '높음'), ('MEDIUM', '중간'), ('LOW', '낮음')], default='MEDIUM', max_length=10, verbose_name='알림 중요도'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('TASK_ASSIGNED', '작업 배정'), ('TASK_STATUS_CHANGED', '작업 상태 변경'), ('TASK_COMMENT', '작업 코멘트'), ('TASK_MENTION', '작업 멘션'), ('TASK_DUE_SOON', '작업 마감 임박'), ('TASK_OVERDUE', '작업 기한 초과'), ('TASK_REVIEWED', '작업 검토 요청'), ('TASK_REVIEW_COMPLETED', '작업 검토 완료'), ('TASK_PRIORITY_CHANGED', '작업 우선순위 변경'), ('TASK_BLOCKED', '작업 차단됨'), ('TASK_UNBLOCKED', '작업 차단 해제'), ('TASK_DEPENDENCY_COMPLETED', '선행 작업 완료')], max_length=30, verbose_name='알림 유형'),
        ),
    ]
